name: Base Container CI

on:
  push:
    paths:
      - 'base.Dockerfile'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-base-container:
    name: Build and Push Base Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Main Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./base.Dockerfile